var X = 2000,
  Y = 10,
  Z = 2;
document.write("X = ", X, "<br>");
document.write("Y = ", Y, "<br>");
document.write("Z = ", Z, "<br>");
document.write("X+Y+Z = ", X + Y + Z, "<br>");
document.write("X-Y+Z = ", X - Y + Z, "<br>");
document.write("X/Y-Z = ", X / Y - Z, "<br>");
document.write("Z/X*Y = ", (Z / X) * Y, "<br>");
document.write("(X%Y)+Z = ", (X % Y) + Z, "<br>");
